### ISSUE TITLE
The gcp auth plugin has been removed.

### ISSUE THREAD

**Issue by danielmapar** [ServiceWeaver/weaver-gke#27]
I am following the steps [here](https://serviceweaver.dev/docs.html#gke) but I am getting:

```bash
Creating cluster serviceweaver-config in location us-central1... Done
internal error: couldn't create clientset for cluster "serviceweaver-config" in region "us-central1": The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details
exit status 1
```

This is my second try. My installation of `gcloud` is fresh and I did install the `gke-gcloud-auth-plugin` component just to be safe (not in the docs). 

```bash
gcloud --version
Google Cloud SDK 420.0.0
bq 2.0.86
core 2023.02.24
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.4.0
gsutil 5.20
kubectl 1.24.10
```

I saw the same issue being reported [here](https://github.com/ServiceWeaver/weaver-gke/issues/25). However, I don't think this problem is fixed yet.

**Comment by danielmapar** [comment]
I noticed the previous [issue](https://github.com/ServiceWeaver/weaver-gke/issues/25) had a PR that was merged to `main`. So I fixed this problem so far by installing `weaver-gke` from `main`:
`go install github.com/ServiceWeaver/weaver-gke/cmd/weaver-gke@main`

**Comment by danielmapar** [comment]
Another problem arises:

```bash
[1]: https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns
-----
Deploying the application... Error
timeout trying to deploy the app; last error: cannot call "https://34.66.11.210/api/v1/namespaces/serviceweaver/services/controller/proxy/controller/rollout": HTTP status 503: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"controller\"","reason":"ServiceUnavailable","code":503}

exit status 1
```

Any ideas? It was able to provision the GKE cluster, the LB, etc. However, it is failing during the `deploy` step.

**Comment by aamonten** [comment]
I'm having the [same issue](https://github.com/ServiceWeaver/weaver-gke/issues/27#issuecomment-1455603764) as mentioned by @danielmapar with respect to "Deploy the application ... error". 

I thought it was my internal Google setup, but apparently not

**Comment by spetrovic77** [comment]
Hi Daniel,

I don't know where my message disappeared. I was able to run end-to-end on a new Cloud Project from my Linux desktop. Are you perhaps running on a MacOS laptop?

Thanks,
-Srdjan

**Comment by danielmapar** [comment]
Yes, I am running on: 

```macOS 13.2.1 (22D68)```

**Comment by danielmapar** [comment]
If you need help debugging, I can jump on a call to simulate the issue with you.

I have been burning GCP projects and making fresh ones to test this deployer.

**Comment by spetrovic77** [comment]
Thanks for your patience!

The issue is that we have been counting on folks developing on Linux, which
was a bad assumption. In particular, we copy the `weaver-gke` binary, as
well as the application binary, from your invoking machine directly into
the Linux container, and then deploy the container on GKE. This is likely a
bad idea, and is why the jobs that run on GKE don't start.

We have to figure out how to solve this issue. You can cross-compile your
application binary, however it's not possible to cross-compile weaver-gke,
since you also end up running it on your local MacOS machine.

**Comment by danielmapar** [comment]
Got it, maybe pulling and re-compiling the weaver-gke inside the Linux
container instead of relying on the precompiled binary from the tar
ball makes more sense.

Let me know if there is any way I can help. However, I appreciate the
explanation.

**Comment by spetrovic77** [comment]
Yeah, we may have to do something like that. It makes GKE development
harder (e.g., make a local change to weaver-gke and test it), but I think
it's more important to get this right for the user.

I'll send a PR for this.

**Comment by spetrovic77** [comment]
I was able to deploy on GKE from an MacOS machine, as of v0.1.4 of GKE.

@danielmapar, could you try and confirm that it works?

**Comment by danielmapar** [comment]
Yes, I was able to deploy! everything working 100% now @spetrovic77
