### ISSUE TITLE
Will there be a v0.5.0 tag?

### ISSUE THREAD

**Issue by p-linnane** [ServiceWeaver/weaver-gke#44]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v0.5.0 of weaver, I noticed there was no matching release for weaver-gke. I wanted to see if there was going to be a release of v0.5.0 or if we should be using v0.4.0 of weaver-gke. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/128105

**Comment by mwhittaker** [comment]
I think v0.4.0 was good, but I just added a v0.5.0 to keep things simple :)

**Comment by p-linnane** [comment]
Thank you!
